import type { LucideIcon } from "lucide-react";
import {
  CreditCard, FileText, Tag, Image, Flag, Briefcase,
  UtensilsCrossed, Monitor, Sparkles, BookOpen,
  GraduationCap, Heart, Layers,
} from "lucide-react";

export interface ServicePricing {
  name: string;
  quantity: string;
  price: string;
}

export interface ServiceFAQ {
  question: string;
  answer: string;
}

export interface Service {
  slug: string;
  name: string;
  shortDescription: string;
  description: string;
  icon: LucideIcon;
  image: string;
  pricing: ServicePricing[];
  faqs: ServiceFAQ[];
}

export const services: Service[] = [
  {
    slug: "business-cards",
    name: "Business Cards",
    shortDescription: "Premium quality business cards with same day collection available.",
    description: "Make a lasting first impression with our premium business cards. Printed on high-quality 400gsm card stock with a range of finishes including matt lamination, gloss lamination, and spot UV. Available in standard and custom sizes.",
    icon: CreditCard,
    image: "/images/business-cards.webp",
    pricing: [
      { name: "Standard Matt", quantity: "100", price: "\u20AC25" },
      { name: "Standard Matt", quantity: "250", price: "\u20AC35" },
      { name: "Standard Matt", quantity: "500", price: "\u20AC55" },
      { name: "Premium Gloss", quantity: "100", price: "\u20AC35" },
      { name: "Premium Gloss", quantity: "250", price: "\u20AC50" },
      { name: "Premium Gloss", quantity: "500", price: "\u20AC75" },
    ],
    faqs: [
      { question: "What size are your business cards?", answer: "Our standard business cards are 85mm x 55mm, the most commonly used size in Ireland and Europe. We also offer custom sizes on request." },
      { question: "Can I get same day business cards?", answer: "Yes! We offer same day click & collect for standard business card orders placed before 12pm. Premium finishes may take 2-3 business days." },
      { question: "What file format should I send?", answer: "We accept PDF, AI, PSD, and high-resolution JPG/PNG files. For best results, send print-ready PDFs with 3mm bleed." },
      { question: "Do you offer design services?", answer: "Yes, we can help design your business cards. Contact us for a quote on our design services." },
      { question: "What finishes are available for business cards?", answer: "We offer matt lamination, gloss lamination, spot UV, soft-touch, and uncoated finishes. Visit our shop at 29-30 Dame St, Dublin 2 to see samples of each finish." },
      { question: "How much do business cards cost in Dublin?", answer: "Our business card printing starts from just \u20AC25 for 100 standard matt cards. Premium finishes and larger quantities are available at competitive prices. Check our pricing table above for full details." },
      { question: "Can I collect my business cards in Dublin city centre?", answer: "Yes! Our print shop is located at 29-30 Dame St, Dublin 2 - right in the heart of Dublin city centre. Click and collect is available for all orders." },
      { question: "What card thickness do you use?", answer: "Our standard business cards are printed on premium 400gsm card stock, giving a sturdy, professional feel. We also offer 300gsm and 600gsm options on request." },
      { question: "Can I order business cards online?", answer: "Yes, you can upload your artwork and order business cards online through our website, or email your files to us. You can also visit us in person at Copyprint.ie on Dame Street." },
      { question: "Do you offer rounded corner business cards?", answer: "Yes, we offer rounded corners as well as other custom finishing options including square-cut, die-cut shapes, and folded business cards." },
    ],
  },
  {
    slug: "flyers-leaflets",
    name: "Flyers & Leaflets",
    shortDescription: "Eye-catching flyers and leaflets for promotions and events.",
    description: "Get your message out there with professionally printed flyers and leaflets. Available in A3, A4, A5, A6, and DL sizes on a variety of paper stocks. Perfect for promotions, events, menus, and marketing campaigns.",
    icon: FileText,
    image: "/images/flyers-leaflets.webp",
    pricing: [
      { name: "A5 Flyers (150gsm)", quantity: "100", price: "\u20AC30" },
      { name: "A5 Flyers (150gsm)", quantity: "250", price: "\u20AC45" },
      { name: "A5 Flyers (150gsm)", quantity: "500", price: "\u20AC65" },
      { name: "A4 Flyers (150gsm)", quantity: "100", price: "\u20AC45" },
      { name: "A4 Flyers (150gsm)", quantity: "250", price: "\u20AC65" },
      { name: "A4 Flyers (150gsm)", quantity: "500", price: "\u20AC95" },
    ],
    faqs: [
      { question: "What paper weights do you offer?", answer: "We offer 130gsm, 150gsm, 170gsm, and 250gsm paper stocks. Heavier weights feel more premium and are great for handouts." },
      { question: "Can I get double-sided printing?", answer: "Absolutely! Double-sided printing is available on all flyer sizes at a small additional cost." },
      { question: "How quickly can I get my flyers?", answer: "Standard turnaround is 2-3 business days. Same day service is available for smaller quantities." },
      { question: "Do you offer folding?", answer: "Yes, we offer half-fold, tri-fold, and Z-fold options for leaflets. Perfect for menus and brochures." },
      { question: "How much do flyers cost to print in Dublin?", answer: "Our flyer printing starts from \u20AC30 for 100 A5 flyers on 150gsm paper. We offer bulk discounts for larger quantities - check our pricing table for full details." },
      { question: "What sizes of flyers and leaflets do you print?", answer: "We print flyers and leaflets in A3, A4, A5, A6, and DL (1/3 A4) sizes. Custom sizes are also available on request." },
      { question: "Can I collect my flyers from your Dublin shop?", answer: "Yes! Click and collect is available from our print shop at 29-30 Dame St, Dublin 2. We're open Monday to Saturday in the heart of Dublin city centre." },
      { question: "What file format do you need for flyer printing?", answer: "We accept print-ready PDFs, AI, PSD, and high-resolution JPG or PNG files. For best results, supply PDFs with 3mm bleed and fonts outlined." },
      { question: "Do you offer delivery for flyer orders?", answer: "Yes, we offer delivery across Dublin and nationwide. Large orders can be delivered directly to your business or event venue." },
      { question: "Can you print flyers on recycled paper?", answer: "Yes, we offer eco-friendly recycled paper options for flyers and leaflets. Ask us about our sustainable printing choices." },
    ],
  },
  {
    slug: "stickers-labels",
    name: "Stickers & Labels",
    shortDescription: "Custom stickers and labels in any shape, size, or finish.",
    description: "Custom printed stickers and labels for products, packaging, promotions, and branding. Available in circles, squares, rectangles, and custom die-cut shapes. Choose from gloss, matt, or transparent vinyl materials.",
    icon: Tag,
    image: "/images/stickers-labels.webp",
    pricing: [
      { name: "Circle Stickers (50mm)", quantity: "100", price: "\u20AC35" },
      { name: "Circle Stickers (50mm)", quantity: "250", price: "\u20AC55" },
      { name: "Rectangle Labels", quantity: "100", price: "\u20AC30" },
      { name: "Rectangle Labels", quantity: "250", price: "\u20AC50" },
      { name: "Custom Die-Cut", quantity: "100", price: "\u20AC45" },
      { name: "Custom Die-Cut", quantity: "250", price: "\u20AC70" },
    ],
    faqs: [
      { question: "Are your stickers waterproof?", answer: "Our vinyl stickers are waterproof and durable, perfect for outdoor use. Paper stickers are best suited for indoor applications." },
      { question: "Can I get custom shaped stickers?", answer: "Yes! We offer custom die-cut stickers in any shape you need. Just send us your design and we'll cut to shape." },
      { question: "What's the minimum order?", answer: "Our minimum order for stickers is 50 units. Contact us for exact pricing on smaller quantities." },
      { question: "How much do custom stickers cost in Dublin?", answer: "Our sticker printing starts from \u20AC30 for 100 rectangle labels. Circle stickers, die-cut shapes, and vinyl options are also competitively priced. See our pricing table for details." },
      { question: "What materials are available for sticker printing?", answer: "We offer gloss paper, matt paper, transparent vinyl, white vinyl, and kraft paper sticker materials. Each is suited to different applications and finishes." },
      { question: "Can I get stickers for product labels and packaging?", answer: "Absolutely! We print high-quality product labels and packaging stickers for food, cosmetics, beverages, and retail products. We can advise on the best material for your needs." },
      { question: "What file format do you need for sticker printing?", answer: "We accept PDF, AI, EPS, PSD, and high-resolution PNG files. For die-cut stickers, please include a cut line on a separate layer in your artwork." },
      { question: "How quickly can I get custom stickers printed?", answer: "Standard sticker orders are ready in 2-3 business days. Rush orders may be available - contact us at our Dame Street shop to discuss your deadline." },
      { question: "Can I order stickers on sheets or individually cut?", answer: "Yes, we offer both options. Stickers can be supplied on sheets (kiss-cut) or individually cut to shape. Sheet stickers are great for giveaways and retail." },
      { question: "Do you print clear or transparent stickers?", answer: "Yes, we print on transparent vinyl material, which is perfect for window stickers, product labels, and branding where you want the surface to show through." },
    ],
  },
  {
    slug: "posters",
    name: "Posters",
    shortDescription: "Vibrant poster printing from A3 to A0 in stunning quality.",
    description: "High-impact poster printing in sizes from A3 to A0 and custom dimensions. Printed on premium poster paper with vivid colours that demand attention. Perfect for advertising, events, retail displays, and art prints.",
    icon: Image,
    image: "/images/posters.webp",
    pricing: [
      { name: "A3 Poster", quantity: "1", price: "\u20AC8" },
      { name: "A3 Poster", quantity: "5", price: "\u20AC30" },
      { name: "A2 Poster", quantity: "1", price: "\u20AC15" },
      { name: "A2 Poster", quantity: "5", price: "\u20AC55" },
      { name: "A1 Poster", quantity: "1", price: "\u20AC25" },
      { name: "A0 Poster", quantity: "1", price: "\u20AC40" },
    ],
    faqs: [
      { question: "What paper do you print posters on?", answer: "We use 200gsm silk or gloss poster paper as standard. We also offer matt, satin, and heavy card options." },
      { question: "Can I get posters laminated?", answer: "Yes! We offer matt and gloss lamination to protect your posters and make them last longer." },
      { question: "Do you print canvas prints?", answer: "We focus on paper poster printing. For canvas prints, please contact us to discuss your requirements." },
      { question: "How much does poster printing cost in Dublin?", answer: "Our poster printing starts from just \u20AC8 for a single A3 poster. A1 and A0 large format posters are also available at competitive prices. See our pricing table for details." },
      { question: "What is the turnaround time for poster printing?", answer: "Single posters can often be printed same day or next day. Larger quantities typically take 2-3 business days. Visit us at 29-30 Dame St, Dublin 2 for fast turnaround." },
      { question: "Can I print a custom size poster?", answer: "Yes! We print posters in custom dimensions as well as standard A3, A2, A1, and A0 sizes. Contact us with your specific size requirements for a quote." },
      { question: "What file format should I send for poster printing?", answer: "We accept PDF, AI, PSD, TIFF, and high-resolution JPG files. For large format posters, ensure your images are at least 150dpi at the final print size." },
      { question: "Can I get posters printed for an event or exhibition?", answer: "Absolutely! We print posters for conferences, exhibitions, trade shows, concerts, and events of all kinds. We can handle rush orders when you need them fast." },
      { question: "Do you offer bulk discounts on poster printing?", answer: "Yes, we offer volume discounts on poster orders. The more you order, the better the per-unit price. Contact us for a quote on your specific quantity." },
      { question: "Can I collect my posters from your Dublin print shop?", answer: "Yes! Click and collect is available from our shop at 29-30 Dame St, Dublin 2. We're centrally located near Trinity College and Grafton Street." },
    ],
  },
  {
    slug: "pvc-banners",
    name: "PVC Banners",
    shortDescription: "Durable outdoor PVC banners with eyelets and hemming.",
    description: "Heavy-duty PVC banners built to last outdoors. Printed on 440gsm PVC material with welded hems and brass eyelets as standard. Perfect for shopfronts, events, construction sites, and promotions. Available in any custom size.",
    icon: Flag,
    image: "/images/pvc-banners.webp",
    pricing: [
      { name: "3ft x 2ft Banner", quantity: "1", price: "\u20AC35" },
      { name: "6ft x 3ft Banner", quantity: "1", price: "\u20AC55" },
      { name: "8ft x 3ft Banner", quantity: "1", price: "\u20AC70" },
      { name: "10ft x 3ft Banner", quantity: "1", price: "\u20AC85" },
      { name: "12ft x 4ft Banner", quantity: "1", price: "\u20AC110" },
      { name: "Custom Size", quantity: "Per sqm", price: "\u20AC25" },
    ],
    faqs: [
      { question: "Are PVC banners suitable for outdoor use?", answer: "Absolutely! Our PVC banners are printed on durable 440gsm material that's weatherproof and UV-resistant." },
      { question: "Do banners come with eyelets?", answer: "Yes, all our PVC banners come with welded hems and brass eyelets at no extra charge, typically every 50cm." },
      { question: "How long do PVC banners last?", answer: "With proper care, our PVC banners can last 3-5 years outdoors. They're built to withstand Irish weather!" },
      { question: "How much do PVC banners cost in Dublin?", answer: "Our PVC banner printing starts from \u20AC35 for a 3ft x 2ft banner. Custom sizes are priced at \u20AC25 per square metre. See our full pricing table above." },
      { question: "What is the turnaround time for PVC banners?", answer: "Standard PVC banner orders are ready in 2-3 business days. Rush and same day service may be available for urgent orders - contact us to discuss." },
      { question: "Can I get a custom size PVC banner?", answer: "Yes! We print PVC banners in any custom size you need. Just let us know your dimensions and we'll provide a quote based on the total area." },
      { question: "What file format do you need for banner printing?", answer: "We accept PDF, AI, EPS, PSD, and high-resolution JPG files. For large banners, images should be at least 150dpi at final print size to ensure sharp results." },
      { question: "Do you offer banner design services?", answer: "Yes, our in-house team at Copyprint.ie can design your PVC banner from scratch or work from your existing branding. Contact us for a design quote." },
      { question: "Can I collect my PVC banner from your Dublin shop?", answer: "Yes! Collection is available from our print shop at 29-30 Dame St, Dublin 2. We also offer delivery across Dublin and nationwide." },
      { question: "Do you print single-sided or double-sided PVC banners?", answer: "We offer both single-sided and double-sided PVC banner printing. Double-sided banners are ideal for hanging displays where both sides are visible." },
    ],
  },
  {
    slug: "business-stationery",
    name: "Business Stationery",
    shortDescription: "Letterheads, compliment slips, envelopes, and NCR pads.",
    description: "Complete business stationery solutions including letterheads, compliment slips, envelopes, NCR pads, and invoice books. Maintain a professional, consistent brand across all your printed communications.",
    icon: Briefcase,
    image: "/images/business-stationery.webp",
    pricing: [
      { name: "Letterheads (A4)", quantity: "250", price: "\u20AC65" },
      { name: "Letterheads (A4)", quantity: "500", price: "\u20AC95" },
      { name: "Compliment Slips", quantity: "250", price: "\u20AC45" },
      { name: "Compliment Slips", quantity: "500", price: "\u20AC65" },
      { name: "NCR Pads (A5, 2-part)", quantity: "5 pads", price: "\u20AC85" },
      { name: "Printed Envelopes", quantity: "250", price: "\u20AC75" },
    ],
    faqs: [
      { question: "Can you match my existing branding?", answer: "Yes! Send us your brand guidelines or existing stationery and we'll match colours and design precisely." },
      { question: "What are NCR pads?", answer: "NCR (No Carbon Required) pads create duplicate or triplicate copies when you write. Perfect for invoices, receipts, and delivery dockets." },
      { question: "Do you print on my own envelopes?", answer: "We can print on most standard envelope sizes. Contact us with your requirements for a quote." },
      { question: "How much does business stationery printing cost?", answer: "Letterhead printing starts from \u20AC65 for 250 sheets. Compliment slips from \u20AC45 for 250. See our full pricing table above for all stationery options." },
      { question: "What paper do you use for letterheads?", answer: "Our standard letterheads are printed on 120gsm uncoated paper for a professional writing surface. We also offer 100gsm and premium textured stocks." },
      { question: "How quickly can you print business stationery?", answer: "Standard stationery orders take 3-5 business days. Letterheads and compliment slips can often be turned around faster. Contact our Dame Street shop for rush orders." },
      { question: "Can I order a complete stationery set with matching designs?", answer: "Yes! We can produce matching letterheads, compliment slips, envelopes, and business cards to give your brand a consistent, professional look." },
      { question: "What file format do you need for stationery printing?", answer: "We accept print-ready PDFs, AI, and PSD files. For letterheads, please include crop marks and 3mm bleed for the best results." },
      { question: "How many parts can NCR pads have?", answer: "We offer 2-part (duplicate) and 3-part (triplicate) NCR pads. They are available in A4 and A5 sizes with 50 sets per pad as standard." },
      { question: "Can I collect my stationery from your Dublin print shop?", answer: "Yes! Collection is available from Copyprint.ie at 29-30 Dame St, Dublin 2. We've been serving Dublin businesses since 1982." },
    ],
  },
  {
    slug: "restaurant-printing",
    name: "Restaurant Printing",
    shortDescription: "Menus, table talkers, loyalty cards, and takeaway materials.",
    description: "Specialised printing for the food and hospitality industry. From elegant dinner menus to takeaway menus, table talkers, loyalty cards, and branded packaging. We understand the unique printing needs of Dublin's restaurants and cafes.",
    icon: UtensilsCrossed,
    image: "/images/restaurant-printing.webp",
    pricing: [
      { name: "A4 Menus (Folded)", quantity: "50", price: "\u20AC45" },
      { name: "A4 Menus (Folded)", quantity: "100", price: "\u20AC65" },
      { name: "A3 Menus (Folded)", quantity: "50", price: "\u20AC65" },
      { name: "Table Talkers", quantity: "25", price: "\u20AC35" },
      { name: "Loyalty Cards", quantity: "250", price: "\u20AC40" },
      { name: "Takeaway Menus (DL)", quantity: "250", price: "\u20AC55" },
    ],
    faqs: [
      { question: "Can menus be laminated?", answer: "Yes! We offer matt and gloss lamination for menus, making them wipeable and durable - perfect for busy restaurants." },
      { question: "How quickly can you print menus?", answer: "Standard menu printing takes 2-3 business days. Rush service is available - just ask!" },
      { question: "Do you design menus?", answer: "Yes, we offer menu design services. We can work from your content and branding to create professional menu layouts." },
      { question: "How much does menu printing cost in Dublin?", answer: "Our menu printing starts from \u20AC45 for 50 A4 folded menus. Takeaway menus, table talkers, and loyalty cards are also competitively priced. See our pricing table above." },
      { question: "What paper is best for restaurant menus?", answer: "For dine-in menus, we recommend 300gsm or 350gsm card with matt or gloss lamination for durability. Takeaway menus work well on 150gsm or 170gsm paper." },
      { question: "Can I get waterproof or wipeable menus?", answer: "Yes! Our laminated menus are wipeable and splash-resistant, perfect for busy restaurants, cafes, and bars. We offer both matt and gloss lamination." },
      { question: "Do you print table talkers and tent cards?", answer: "Yes, we print table talkers, tent cards, and counter cards on sturdy card stock. They're perfect for promoting specials, desserts, and drinks in your restaurant." },
      { question: "What file format do you need for menu printing?", answer: "We accept print-ready PDFs, AI, PSD, and high-resolution image files. If you need help with layout, our design team can create your menu for you." },
      { question: "Can you print loyalty cards for my restaurant or cafe?", answer: "Yes! We print loyalty cards on durable 400gsm card stock. They're a great way to encourage repeat customers. Available from just \u20AC40 for 250 cards." },
      { question: "Do you offer delivery for restaurant print orders?", answer: "Yes, we deliver across Dublin and nationwide. You can also collect from our shop at 29-30 Dame St, Dublin 2 - conveniently located in Dublin city centre." },
    ],
  },
  {
    slug: "roller-banners",
    name: "Roller Banners",
    shortDescription: "Professional pull-up roller banners for events and exhibitions.",
    description: "Professional retractable roller banners that make a big impact at events, exhibitions, and in your premises. Easy to set up in seconds, portable, and reusable. Available in standard 850mm x 2000mm and custom sizes.",
    icon: Monitor,
    image: "/images/roller-banners.webp",
    pricing: [
      { name: "Standard (850x2000mm)", quantity: "1", price: "\u20AC85" },
      { name: "Standard (850x2000mm)", quantity: "2", price: "\u20AC150" },
      { name: "Premium (850x2000mm)", quantity: "1", price: "\u20AC120" },
      { name: "Wide (1200x2000mm)", quantity: "1", price: "\u20AC140" },
      { name: "Replacement Print Only", quantity: "1", price: "\u20AC45" },
    ],
    faqs: [
      { question: "How long does it take to set up a roller banner?", answer: "Roller banners take about 30 seconds to set up. Simply pull up the banner from the base and attach the support pole." },
      { question: "Can I replace just the print?", answer: "Yes! If your stand is still in good condition, we can print a replacement graphic at a reduced cost." },
      { question: "Are roller banners suitable for outdoor use?", answer: "Roller banners are designed primarily for indoor use. For outdoor events, we recommend our PVC banners instead." },
      { question: "How much do roller banners cost in Dublin?", answer: "Our standard roller banners start from \u20AC85 including the stand and printed graphic. Premium and wide options are also available. See our pricing table for full details." },
      { question: "What size are your roller banners?", answer: "Our standard roller banners are 850mm wide x 2000mm tall. We also offer wide format options at 1200mm x 2000mm and custom sizes on request." },
      { question: "Do roller banners come with a carry case?", answer: "Yes, all our roller banners come with a padded carry case for easy transport to events, exhibitions, and trade shows." },
      { question: "What file format do you need for roller banner artwork?", answer: "We accept PDF, AI, PSD, and high-resolution JPG files. Artwork should be supplied at 850mm x 2000mm with 150dpi minimum resolution." },
      { question: "How quickly can I get a roller banner printed?", answer: "Standard roller banner orders are ready in 2-3 business days. Express service is available for urgent orders - contact us at our Dame Street print shop." },
      { question: "Can I collect my roller banner from your Dublin shop?", answer: "Yes! Collection is available from Copyprint.ie at 29-30 Dame St, Dublin 2 - right in Dublin city centre, near Trinity College and Grafton Street." },
      { question: "How long do roller banners last?", answer: "With proper care and storage, roller banner stands can last for years. The printed graphic typically looks great for 12-18 months of regular use, and replacements are available from \u20AC45." },
    ],
  },
  {
    slug: "party-banners",
    name: "Party Banners",
    shortDescription: "Personalised party banners for birthdays, communions, and events.",
    description: "Make any celebration extra special with personalised party banners. Perfect for birthdays, christenings, communions, confirmations, graduations, and special occasions. Add photos, custom text, and choose your colours.",
    icon: Sparkles,
    image: "/images/party-banners.webp",
    pricing: [
      { name: "Small (3ft x 1ft)", quantity: "1", price: "\u20AC20" },
      { name: "Medium (5ft x 2ft)", quantity: "1", price: "\u20AC35" },
      { name: "Large (6ft x 3ft)", quantity: "1", price: "\u20AC50" },
      { name: "Extra Large (8ft x 3ft)", quantity: "1", price: "\u20AC65" },
      { name: "Custom Size", quantity: "1", price: "From \u20AC25" },
    ],
    faqs: [
      { question: "Can I add photos to my party banner?", answer: "Absolutely! Send us your favourite photos and we'll incorporate them into your banner design." },
      { question: "How quickly can I get a party banner?", answer: "Party banners are often needed at short notice - we can usually turn them around in 24 hours or same day if needed." },
      { question: "What material are party banners printed on?", answer: "Party banners are printed on durable PVC material, suitable for both indoor and outdoor use." },
      { question: "How much do personalised party banners cost?", answer: "Our party banners start from just \u20AC20 for a small 3ft x 1ft banner. Larger sizes and custom dimensions are available. See our pricing table for all options." },
      { question: "Can I get a same day party banner in Dublin?", answer: "Yes! We understand party banners are often needed at short notice. Same day and next day turnaround is available from our shop at 29-30 Dame St, Dublin 2." },
      { question: "What occasions can I order a party banner for?", answer: "We print personalised banners for birthdays, christenings, communions, confirmations, graduations, hen parties, retirements, anniversaries, and any special celebration." },
      { question: "Can I choose my own colours and design for a party banner?", answer: "Absolutely! You choose the colours, text, photos, and theme. We can also work from a design you provide, or create a custom design for you." },
      { question: "What sizes of party banners do you offer?", answer: "We offer party banners from 3ft x 1ft up to 8ft x 3ft, plus custom sizes. Whether you need a small indoor banner or a large outdoor one, we have you covered." },
      { question: "Do you offer party banner design templates?", answer: "Yes, we have a range of popular templates for birthdays, communions, and other celebrations. We can customise these with your text, photos, and colours." },
      { question: "Can I collect my party banner from your Dublin shop?", answer: "Yes! Click and collect is available from Copyprint.ie at 29-30 Dame St, Dublin 2. We're centrally located in Dublin city centre for easy collection." },
    ],
  },
  {
    slug: "booklets",
    name: "Booklets",
    shortDescription: "Saddle-stitched and perfect bound booklets and brochures.",
    description: "Professional booklet and brochure printing with saddle-stitching or perfect binding. Ideal for company profiles, product catalogues, event programmes, training manuals, and reports. Available in A4, A5, and custom sizes.",
    icon: BookOpen,
    image: "/images/booklets.webp",
    pricing: [
      { name: "A5 Booklet (8 pages)", quantity: "50", price: "\u20AC95" },
      { name: "A5 Booklet (8 pages)", quantity: "100", price: "\u20AC150" },
      { name: "A5 Booklet (16 pages)", quantity: "50", price: "\u20AC140" },
      { name: "A4 Booklet (8 pages)", quantity: "50", price: "\u20AC130" },
      { name: "A4 Booklet (16 pages)", quantity: "50", price: "\u20AC195" },
    ],
    faqs: [
      { question: "What's the difference between saddle-stitch and perfect binding?", answer: "Saddle-stitching uses staples through the spine - ideal for booklets up to about 48 pages. Perfect binding uses a glued spine like a paperback book, suitable for thicker publications." },
      { question: "What's the minimum page count?", answer: "Saddle-stitched booklets need a minimum of 8 pages (including covers). Page count must be in multiples of 4." },
      { question: "Can you help with layout and design?", answer: "Yes! We offer booklet design and layout services. We can work from your content to create a professional publication." },
      { question: "How much does booklet printing cost in Dublin?", answer: "Our booklet printing starts from \u20AC95 for 50 copies of an 8-page A5 booklet. Prices vary by size, page count, and quantity. See our pricing table for full details." },
      { question: "What paper do you use for booklets?", answer: "We use 150gsm silk or gloss paper for inner pages and 300gsm card for covers as standard. Matt, uncoated, and recycled paper options are also available." },
      { question: "What is the turnaround time for booklet printing?", answer: "Standard booklet orders take 3-5 business days. Rush service may be available for smaller quantities - contact us at our Dame Street shop to discuss." },
      { question: "What file format do you need for booklet printing?", answer: "We accept print-ready PDFs with pages in the correct order. We handle the imposition for you. AI, PSD, and InDesign files are also accepted." },
      { question: "Can I print booklets in custom sizes?", answer: "Yes! In addition to standard A4 and A5 sizes, we can print booklets in custom dimensions including square formats and DL size." },
      { question: "Do you print event programmes and catalogues?", answer: "Absolutely! We print event programmes, product catalogues, company profiles, training manuals, annual reports, and all types of multi-page publications." },
      { question: "Can I collect my booklets from your Dublin print shop?", answer: "Yes! Collection is available from Copyprint.ie at 29-30 Dame St, Dublin 2. We also offer delivery across Dublin and nationwide for larger orders." },
    ],
  },
  {
    slug: "student-services",
    name: "Student Services",
    shortDescription: "Affordable printing for students - theses, assignments, and more.",
    description: "Student-friendly printing services at affordable prices. We're just minutes from Trinity College, DIT, and Dublin's city centre colleges. Print and bind your thesis, assignments, portfolios, and presentations with our fast, reliable service.",
    icon: GraduationCap,
    image: "/images/student-services.webp",
    pricing: [
      { name: "B&W Printing (A4)", quantity: "Per page", price: "\u20AC0.10" },
      { name: "Colour Printing (A4)", quantity: "Per page", price: "\u20AC0.30" },
      { name: "Thesis Binding (Soft)", quantity: "1", price: "\u20AC12" },
      { name: "Thesis Binding (Hard)", quantity: "1", price: "\u20AC25" },
      { name: "Poster Printing (A1)", quantity: "1", price: "\u20AC20" },
      { name: "Laminating (A4)", quantity: "1", price: "\u20AC3" },
    ],
    faqs: [
      { question: "Do you offer student discounts?", answer: "Our student prices are already very competitive! We pride ourselves on offering student-friendly rates. Show your student ID for the best deals." },
      { question: "Can I print from a USB drive?", answer: "Yes! Bring your files on a USB drive, email them to us, or use our online upload. We accept all common file formats." },
      { question: "Do you bind theses to college specifications?", answer: "Yes, we're very familiar with the binding requirements for Trinity, UCD, DCU, and other Dublin colleges. We'll make sure your thesis meets the specifications." },
      { question: "How quickly can I get my thesis bound?", answer: "Soft binding can be done while you wait. Hard case binding typically takes 3-5 business days." },
      { question: "Where is your print shop located near Dublin colleges?", answer: "We're at 29-30 Dame St, Dublin 2 - just a few minutes' walk from Trinity College Dublin, and easily accessible from UCD, DCU, DIT, and other Dublin colleges." },
      { question: "What file formats do you accept for student printing?", answer: "We accept PDF, Word, PowerPoint, and all common file formats. You can email your files, upload online, or bring them on a USB drive." },
      { question: "Can I print in colour and black & white in the same document?", answer: "Yes! We can mix colour and black & white pages in the same document to keep your costs down. Just let us know which pages need colour." },
      { question: "Do you print academic posters for presentations?", answer: "Yes, we print A1 and A0 academic posters for student presentations and conferences. Posters start from just \u20AC20 for A1 size." },
      { question: "Can I get my assignment printed and bound same day?", answer: "Yes! Printing and soft binding can usually be done while you wait. Walk into our Dame Street shop with your files and we'll have you sorted quickly." },
      { question: "Do you offer bulk printing discounts for students?", answer: "Yes, the more pages you print, the lower the per-page cost. We offer very competitive rates for large print runs of notes, handouts, and study materials." },
    ],
  },
  {
    slug: "personal-printing",
    name: "Personal Printing",
    shortDescription: "Wedding invitations, photo prints, greeting cards, and more.",
    description: "Beautiful printing for life's special moments. From wedding invitations and save-the-dates to photo prints, greeting cards, calendars, and personalised gifts. We bring your personal projects to life with care and quality.",
    icon: Heart,
    image: "/images/personal-printing.webp",
    pricing: [
      { name: "Wedding Invitations", quantity: "50", price: "\u20AC75" },
      { name: "Wedding Invitations", quantity: "100", price: "\u20AC120" },
      { name: "Save the Date Cards", quantity: "50", price: "\u20AC45" },
      { name: "Photo Prints (6x4)", quantity: "25", price: "\u20AC15" },
      { name: "Photo Prints (A4)", quantity: "10", price: "\u20AC25" },
      { name: "Greeting Cards", quantity: "25", price: "\u20AC35" },
    ],
    faqs: [
      { question: "Can you help design wedding invitations?", answer: "Yes! We offer a wedding stationery design service. We'll work with you to create the perfect invitations for your big day." },
      { question: "What paper do you use for invitations?", answer: "We offer a range of premium papers including textured, linen, and pearlescent finishes. Pop into our shop to see and feel the samples." },
      { question: "Do you print matching wedding stationery sets?", answer: "Absolutely! We can print matching invitations, RSVP cards, save-the-dates, mass booklets, table plans, and thank you cards." },
      { question: "How much do wedding invitations cost to print in Dublin?", answer: "Our wedding invitation printing starts from \u20AC75 for 50 invitations. We offer a range of paper stocks and finishes to suit every budget and style." },
      { question: "What is the turnaround time for wedding invitations?", answer: "Wedding invitation orders typically take 5-7 business days. We recommend ordering at least 8-10 weeks before your wedding. Rush orders may be available on request." },
      { question: "Can I print personalised photo gifts?", answer: "Yes! We print personalised photo prints, calendars, greeting cards, and other custom photo products. Bring your favourite images and we'll create something special." },
      { question: "What file format do you need for personal printing?", answer: "We accept PDF, JPG, PNG, and TIFF files. For photo prints, we recommend high-resolution images of at least 300dpi for the best quality results." },
      { question: "Do you print christening and communion invitations?", answer: "Yes, we print invitations and stationery for christenings, communions, confirmations, and all religious celebrations. We can also print mass booklets and thank you cards." },
      { question: "Can I see paper samples before ordering?", answer: "Of course! Visit our shop at 29-30 Dame St, Dublin 2 to see and feel our range of paper samples including textured, linen, pearlescent, and recycled options." },
      { question: "Do you offer delivery for personal printing orders?", answer: "Yes, we offer delivery across Dublin and nationwide. You can also collect from our Dame Street shop in Dublin city centre. We've been here since 1982!" },
    ],
  },
  {
    slug: "laminating-binding",
    name: "Laminating & Binding",
    shortDescription: "Document laminating and professional binding services.",
    description: "Protect and present your documents professionally with our laminating and binding services. From laminating single pages to binding full reports and presentations, we have the right finish for your documents.",
    icon: Layers,
    image: "/images/laminating-binding.webp",
    pricing: [
      { name: "Laminating (A4)", quantity: "1", price: "\u20AC3" },
      { name: "Laminating (A3)", quantity: "1", price: "\u20AC5" },
      { name: "Comb Binding", quantity: "1", price: "\u20AC5" },
      { name: "Wire Binding", quantity: "1", price: "\u20AC7" },
      { name: "Soft Cover Binding", quantity: "1", price: "\u20AC12" },
      { name: "Hard Case Binding", quantity: "1", price: "\u20AC25" },
    ],
    faqs: [
      { question: "What types of laminating do you offer?", answer: "We offer gloss and matt laminating in sizes from business card up to A1. Gloss gives a shiny finish while matt gives a more subtle, professional look." },
      { question: "Can I get documents bound while I wait?", answer: "Comb binding and wire binding can usually be done while you wait. Soft and hard cover binding may take 1-3 business days." },
      { question: "What's the best binding for a thesis?", answer: "For final thesis submission, most colleges require hard case binding. For draft submissions, soft cover binding is a great option." },
      { question: "How much does laminating cost in Dublin?", answer: "A4 laminating starts from just \u20AC3 per sheet. A3 laminating is \u20AC5 per sheet. We offer discounts for bulk laminating orders. See our full pricing table above." },
      { question: "What binding options do you offer?", answer: "We offer comb binding, wire binding, soft cover (thermal) binding, and hard case binding. Each option suits different document types and budgets." },
      { question: "Can I get documents laminated while I wait?", answer: "Yes! Laminating is a quick service and can usually be done while you wait. Visit us at 29-30 Dame St, Dublin 2 for fast laminating." },
      { question: "What sizes can you laminate?", answer: "We laminate documents from business card size up to A1. Standard sizes include A4, A3, A2, and A1. Custom sizes are also available." },
      { question: "How much does binding cost in Dublin?", answer: "Comb binding starts from \u20AC5, wire binding from \u20AC7, soft cover from \u20AC12, and hard case binding from \u20AC25. Prices depend on document thickness and finish." },
      { question: "Do you offer encapsulating (pouched) lamination?", answer: "Yes, we offer both pouched lamination for smaller items and roll lamination for larger documents. Pouched lamination fully seals the document for maximum protection." },
      { question: "Can I get my documents printed and bound in one visit?", answer: "Absolutely! We offer a complete print and bind service. Bring your files on USB or email them to us, and we can print and bind your documents in one visit to our Dame Street shop." },
    ],
  },
];

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug);
}
